version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  api-module:
    image: avgulavani/weather-docker
    container_name: api-module
    depends_on:
      - chrome
      - firefox
    environment:
      - MODULE=uitestng.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - ./weathertest-api-result:/usr/share/weathertest-api/test-output

      
    volumes:
      - ./weather-test-result:/usr/share/weather/test-output